-- CRIANDO
CREATE DATABASE LOJINHA_DO_TIO;
-- USANDO
USE LOJINHA_DO_TIO;

DROP DATABASE LOJINHA_DO_TIO;

-- TABELAS
CREATE TABLE IF NOT EXISTS PERSON (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL, -- Não nulo
    AGE INT NOT NULL,
    EMAIL VARCHAR(60) NOT NULL,
    PHONE VARCHAR(13),
    UNIQUE KEY(NAME, EMAIL, PHONE), 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ROLE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRIPTION VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
    
CREATE TABLE IF NOT EXISTS USER (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(15) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    PERSON_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS CATEGORY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS BRAND (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_NAME VARCHAR(25) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (BRAND_NAME)
    );
    
CREATE TABLE IF NOT EXISTS PRODUCT (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    BRAND_ID INT NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL,
    QTD_STOCK INT NOT NULL DEFAULT(0),
    VALUE DECIMAL(10,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	PRODUCT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE
    );

# ----------------------------------------
INSERT INTO PERSON (NAME, AGE, EMAIL, PHONE, CREATED_AT) VALUES
('Carlos Silva', 30, 'carlos@email.com', '11999999999', '2024-02-01 10:00:00');
INSERT INTO PERSON (NAME, AGE, EMAIL, PHONE, CREATED_AT) VALUES
('Pedro Afonso', 18, 'pedro-afonso@email.com', '11999999999', '2024-02-01 10:00:00');

# ----------------------------------------

-- Inserindo dados na tabela PERSON
INSERT INTO PERSON (NAME, AGE, EMAIL, PHONE, CREATED_AT) VALUES
('Ana Souza', 25, 'ana@email.com', '11888888888', '2024-02-02 11:15:00'),
('Mariana Lima', 35, 'mariana@email.com', '11777777777', '2024-02-03 09:30:00'),
('Pedro Henrique', 28, 'pedro@email.com', '11666666666', NOW()),
('Juliana Costa', 32, 'juliana@email.com', '11555555555', NOW());

-- Inserindo dados na tabela ROLE
INSERT INTO ROLE (DESCRIPTION, CREATED_AT) VALUES
('Administrador', '2024-02-01 08:00:00'),
('Vendedor', '2024-02-02 09:30:00'),
('Estoquista', '2024-02-03 10:45:00');

-- Inserindo dados na tabela USER
INSERT INTO USER (LOGIN, PASSWORD, PERSON_ID, ROLE_ID, CREATED_AT) VALUES
('carlos_s', '123456', 1, 1, '2024-02-01 12:00:00'),
('ana_s', 'abcdef', 2, 2, '2024-02-02 13:30:00'),
('mariana_l', '654321', 3, 3, NOW()),
('pedro_h', 'pass123', 4, 2, NOW()),
('juliana_c', 'juliana123', 5, 3, NOW());

-- Inserindo dados na tabela CATEGORY
INSERT INTO CATEGORY (DESCRIPTION, CREATED_AT) VALUES
('Eletrônicos', '2024-02-01 14:00:00'),
('Móveis', '2024-02-02 15:30:00'),
('Brinquedos', NOW()),
('Roupas', NOW());

-- Inserindo dados na tabela BRAND
INSERT INTO BRAND (BRAND_NAME, CREATED_AT) VALUES
('Samsung', '2024-02-01 16:00:00'),
('LG', '2024-02-02 17:30:00'),
('Sony', NOW()),
('Nike', NOW());

-- Inserindo dados na tabela PRODUCT
INSERT INTO PRODUCT (NAME, BRAND_ID, DESCRIPTION, QTD_STOCK, VALUE, CREATED_AT) VALUES
('Smartphone Galaxy', 1, 'Celular Samsung de última geração', 50, 2999.99, '2024-02-01 18:00:00'),
('Smart TV 50"', 2, 'Televisão 4K com Wi-Fi', 30, 3999.99, '2024-02-02 19:30:00'),
('PlayStation 5', 3, 'Console de última geração', 20, 4999.99, NOW()),
('Tênis Esportivo', 4, 'Tênis confortável para corrida', 100, 299.99, NOW());

-- Inserindo dados na tabela PRODUCT_CATEGORY
INSERT INTO PRODUCT_CATEGORY (PRODUCT_ID, CATEGORY_ID, CREATED_AT) VALUES
(1, 1, '2024-02-01 20:00:00'), -- Smartphone Galaxy pertence à categoria Eletrônicos
(2, 1, '2024-02-02 21:30:00'), -- Smart TV pertence à categoria Eletrônicos
(3, 1, NOW()), -- PlayStation 5 pertence à categoria Eletrônicos
(4, 4, NOW()); -- Tênis Esportivo pertence à categoria Roupas