USE LOJINHA_DO_TIO;

-- SELECIONA TODO MUNDO
SELECT * FROM PERSON;

-- SELECIONA TUDO SOBRE O CARLOS SILVA
SELECT * FROM PERSON WHERE NAME = "Carlos Silva";

SELECT * FROM PERSON WHERE CREATED_AT > '2024-02-03 00:00:00';

-- BETWEEN = ENTRE
SELECT * FROM PERSON WHERE CREATED_AT BETWEEN '2024-02-02 00:00:00' AND '2024-02-03 10:00:00';

-- SELECIONA AS PESSOAS COM IDADE ENTRE 25 E 35 ANOS
SELECT * FROM PERSON WHERE AGE BETWEEN 30 AND 35;

SELECT * FROM PRODUCT;

-- Quando quero selecionar entre um conjunto de intervalos IN
SELECT * FROM PRODUCT WHERE BRAND_ID IN (1,2);

SELECT * FROM USER;

-- SELECIONAR LOGINS QUE COMEÇAM COM A LETRA A
SELECT * FROM USER WHERE LOGIN LIKE 'a%';

-- SELECIONAR LOGINS QUE TERMINAM COM A LETRA S
SELECT * FROM USER WHERE LOGIN LIKE '%S';

-- SELECINAR LOGINS QUE TENHAM A LETRA A
SELECT * FROM USER WHERE LOGIN LIKE '%a%';

SELECT * FROM PERSON;

-- SELECIONAR PESSOAR QUE TENHAM IA NO MEIO DO NOME
SELECT * FROM PERSON WHERE NAME LIKE '%ia%';

-- PRO LAR
SELECT * FROM PERSON WHERE NAME LIKE '%i%%a%';

-- SELECIONAR PESSOA QUE COMEÇA COM P E TERMINA COM O
SELECT * FROM PERSON WHERE NAME LIKE 'p%o';

-- SELECIONANDO PESSOA QUE TENHA 12 CARACTERES NO NOME, INCLUINDO O ESPAÇO
SELECT * FROM PERSON WHERE NAME LIKE '____________';

-- SELECIINA UM NOME QUE TEM 11 CARACTERES ANTES DO A, E TRAS O RESTANTE DEPOIS DO A
SELECT * FROM PERSON WHERE NAME LIKE '___________a%';

-- SELECIONA UM NOME QUE TEM 11 CARACTERES E TERMINA COM A LETRA A
SELECT * FROM PERSON WHERE NAME LIKE '____________a';

-- SELECIONA UM NOME QUE TEM 5 CARACTERES ANTES DO S, E TRAS O RESTANTE DEPOIS DO S;
SELECT * FROM PERSON WHERE NAME LIKE '_____s%';

-- SELECIONA UM NOME QUE TEM 5 CARACTERES ANTES DO S E 5 CARACTERES DEPOIS DO S.
SELECT * FROM PERSON WHERE NAME LIKE '_____s%____';

SELECT * FROM PRODUCT;

-- BUSCANDO O MAIOR VALOR DE VALUE DA TABELA PRODUTO
SELECT MAX(VALUE) FROM PRODUCT;

-- AS = ALIAS -> RENOMEIA SÓ PARA VISUALIZAÇÃO
SELECT MAX(VALUE) AS VALOR_MAIOR FROM PRODUCT;

-- BUSCANDO INFO DO PRODUTO DE VALOR 4999.99
SELECT * FROM PRODUCT WHERE VALUE = 4999.99;

-- OBTER TODAS AS INFORMAÇÕES DO PRODUTO MAIS CARO
SELECT * FROM PRODUCT WHERE VALUE = (SELECT MAX(VALUE) FROM PRODUCT);

INSERT INTO PRODUCT (NAME, BRAND_ID, DESCRIPTION, QTD_STOCK, VALUE, CREATED_AT) VALUES
('iPhone', 1, 'Iphone 14', 10, 4999.99, '2024-02-01 18:00:00');

